app/weather/__init__.py
from flask import Blueprint

weatherBP = Blueprint("weather", __name__, template_folder="templates")

from . import routes

app/weather/routes.py
import logging
from flask import flash, request, render_template, url_for, redirect, session
from . import weatherBP
from ..models.weatherapp import LocationException, WeatherObject
from ..models.database import databaseConnection
import secrets
from ..constants.constants import DEFAULT_LOCATION
from app import weather

secretKey = secrets.token_bytes(16)
dbConn = databaseConnection()
db = dbConn.db
cursor = db.cursor()

weatherApp = WeatherObject()


@weatherBP.route("/current", methods=["POST", "GET"])
def current():
    signedIn = False
    today = ""
    dt = ""
    locationInfo = {}
    if request.method == "POST":
        location = request.form["locationInp"]
        error = weatherApp.setLocation("today", location)
        if error != "":
            return render_template(
                "weather.html",
                today=today,
                signedIn=signedIn,
                username=session.get("username"),
                dt=dt,
                location=location,
                locationInfo=locationInfo,
            )
    else:
        username = session.get("username")
        if username is not None:
            logging.log(logging.DEBUG, "User is logged in")
            sql = "SELECT * from WeatherData WHERE userID =%s"
            cursor.execute(sql, [session.get("id")])
            result = cursor.fetchone()
            if result:
                error = weatherApp.setLocation("today", result[2])
                if error != "":
                    return render_template("error.html", error=error)

            # check if their location is set then set the location and show the current weather for that place using setLocation()
            signedIn = True

            # Search for users saved location here
        else:
            logging.log(logging.DEBUG, "User is not logged in")
    temperatures = ["temp", "feels_like", "temp_min", "temp_max"]
    for key, value in weatherApp.today["main"].items():
        if key in temperatures:
            weatherApp.today["main"][key] = weatherApp.kelvinToCelcius(value)

    weatherApp._checkDate(weatherApp.today["dt"])

    location = weatherApp.location

    today = weatherApp.today
    dt = weatherApp.unixToUTC(today["dt"])
    logging.log(logging.DEBUG, "Rendering complete page now")
    error, locationInfo = weatherApp.checkLocation(location)
    return render_template(
        "weather.html",
        today=today,
        username=session.get("username"),
        dt=dt,
        location=location,
        locationInfo=locationInfo,
        error="",
    )


@weatherBP.route("/forecast", methods=["POST", "GET"])
def forecast():
    error = ""
    location = ""
    forecastList = []
    indexes = []
    username = session.get("username")
    id = session.get("id")
    if request.method == "POST":
        location = request.form["locationInp"]
        error, locationInfo = weatherApp.checkLocation(location)
        if error == "":
            forecastLocation = location
        else:
            logging.log(logging.ERROR, error)
            return render_template(
                "forecast.html", list=forecastList, indexes=indexes, error=error
            )
    elif username is not None:
        try:
            sql = "SELECT location from WeatherData where userID = %s"
            cursor.execute(sql, [session.get("id")])
            result = cursor.fetchone()
            if result:
                forecastLocation = result[0]
            else:
                forecastLocation = DEFAULT_LOCATION
        except Exception as e:
            forecastLocation = DEFAULT_LOCATION
            raise (e)

    else:
        forecastLocation = DEFAULT_LOCATION

    if forecastLocation:
        forecastList, error = setLocation("forecast", forecastLocation)
        if forecastList is None:
            return render_template(
                "forecast.html", list=forecastList, indexes=indexes, error=error
            )

        indexes = weatherApp.indexOfTimes(forecastList["list"], 22)

    return render_template(
        "forecast.html", list=forecastList, indexes=indexes, error=error
    )


def setLocation(weatherType, location):
    try:
        weatherApp.setLocation(weatherType, location)
    except LocationException as e:
        return None, e
    forecastList = weatherApp.list
    error = None
    return forecastList, error

app/weather/templates/forecast.html
{% extends "base.html" %}

{% block head %}
<h1>Forecast Page</h1>
{% endblock %}

{% block body %}

{% if error != None %}
<p class = "errorMessage">{{error}}</p>
{% endif %}

<form action ="{{url_for('weather.forecast')}}" method="POST" class="forecastForm">
        <label for="locationInp">Enter location: </label>
        <input type= "text" id= "locationInp" name= "locationInp" placeholder="e.g. London">
        <input type="submit" id= "locationSubmit" name= "locationSubmit" value="Submit">
</form>
{% if list != [] and indexes != []%}
    <h2 class="forecastTitle">Forecast for {{list["city"]["name"]}} - {{list["city"]["country"]}}</h2>

    <ul class="forecastList">
        {% for item in list["list"]%}
            {% if item["pop"] == 0 %}
                {% set rain = "" %}
            {% else %}
                {% set rain = ", Chance of rain: {}%".format(item["pop"]*100) %}
            {% endif %}
            <li class="forecast-item">
              <div class="forecast-content">
                <img class="forecast-img" src="https://openweathermap.org/img/wn/{{ item["weather"][0]["icon"] }}@2x.png" alt="Weather Icon">
                <div class="forecast-details">
                <strong>{{ item["dt"] }}</strong><strong>{{item["weather"][0]["description"].title()}}</strong> - Temperature: {{ item["main"]["temp"] }}°C, Feels like: {{ item["main"]["feels_like"] }}°C {{ rain }}
                </div>
              </div>
            </li>
        {% endfor%}
    </ul>
{% endif %}

{% endblock %}

app/weather/templates/weather.html
{% extends "base.html" %}


{% block body %}

{% if error != "" %}
<p class="errorMessage">{{error}}</p>
{% endif %}

    <div class = "weather-container">
    <h1>Current Weather</h1>
 
    <div class = "search-box">
    <form action ="{{url_for('weather.current')}}" method="POST">
        <input type= "text" id= "locationInp" name= "locationInp" placeholder="Enter a location, e.g. London">
        <input type="submit" id= "locationSubmit" name= "locationSubmit" value="Search">
    </form>
    </div>
<p>{{error}}</p>
{% if error == "" %}

<div class = "weather-info">
<div class= "weather-header">
    {% if locationInfo != {} %}
    <img src = "https://openweathermap.org/img/wn/{{locationInfo.weatherIcon}}@4x.png"</img>

    {% endif %}
<div class="weather-location">
    <strong>{{dt}} IN {{today["name"]}}{% if today["name"] != location %}, {{location}}{% endif %}</strong>

    <p>Temperature is currently {{today["main"]["temp"]}}°C degrees and feels like {{today["main"]["feels_like"]}}°C</p>

    <p>High: {{today["main"]["temp_max"]}} || Low: {{today["main"]["temp_min"]}}</p>
    <p>Humidity: {{today["main"]["humidity"]}}%</p>
    <p>Wind: {{today["wind"]["speed"]}} m/s (Gusts up to 6.81m/s)</p>
</div>
</div>

</div>
    
{% endif %}

   </div>
{% endblock %}