app/account/__init__.py
from flask import Blueprint

accountBP = Blueprint("account", __name__, template_folder="templates")

from . import routes

app/account/routes.py
import logging
from app.models.weatherapp import WeatherObject
from . import accountBP

weatherApp = WeatherObject()
from flask import redirect, render_template, session, url_for, request

from ..models.database import databaseConnection

dbConn = databaseConnection()
db = dbConn.db
cursor = db.cursor()


@accountBP.route("/account")
def account():
    error = ""
    loggedIn = False
    username = session.get("username")
    if username is not None:
        loggedIn = True
        sql = "SELECT preferences.heat, WeatherData.location from preferences join WeatherData on preferences.userID = WeatherData.userID where preferences.userID = %s"
        cursor.execute(sql, [session.get("id")])
        result = cursor.fetchone()
        if result is None:
            return redirect(url_for("account.setPreferences"))

        error, locationInfo = weatherApp.checkLocation(result[1])
        print(locationInfo)
        locationPreference, heatPreference = result[1], result[0]

        return render_template(
            "account.html",
            loggedIn=loggedIn,
            locationPreference=locationPreference,
            locationInfo=locationInfo,
            heatPreference=heatPreference,
            error=error,
        )

    return render_template("account.html", error=error)


@accountBP.route("/setPreferences")
def setPreferences():
    error = ""
    return render_template("setPreferences.html", error=error)


@accountBP.route("/submitPreferences", methods=["POST"])
def submitPreferences():
    username = session.get("username")
    logging.log(1, f"{username} username ")
    if username is None:
        return redirect(url_for("account.account"))
    location = request.form["location"]
    error, data = weatherApp.checkLocation(location)
    if error != "":
        return render_template("setPreferences.html", error=error)

    preference = request.form["preference"]
    sql = "INSERT INTO WeatherData (userID, location) VALUES (%s, %s)"
    cursor.execute(sql, [session.get("id"), location])
    db.commit()
    sql = "INSERT INTO preferences (userID, heat) VALUES (%s, %s)"
    cursor.execute(sql, [session.get("id"), preference.title()])
    db.commit()
    session["location"] = location
    session["preference"] = preference
    return redirect(url_for("main.index"))


@accountBP.route("/changePreferences", methods=["POST", "GET"])
def changePreferences():
    if request.method == "POST":
        newLocation = request.form["newLocation"]
        newHeat = request.form["heatPreference"]
        if newLocation != "":
            # set it
            sql = "UPDATE WeatherData SET location= %s WHERE userID= %s"
            cursor.execute(sql, [newLocation, session.get("id")])
        if newHeat != "":
            # set it
            sql = "UPDATE preferences set heat= %s WHERE userID= %s"
            cursor.execute(sql, [newHeat, session.get("id")])
        db.commit()
        return redirect(url_for("account"))
    else:
        return render_template("changePreferences.html")

app/account/templates/account.html
{% extends "base.html" %}
{% block body %}
{% if error != "" %}
<p class="errorMessage">{{error}}</p>
{% endif %}
{% if not loggedIn %}
<div class="authContainer">
<div class="signupForm">
<h3>Signup form</h3>
    <form action="{{url_for("auth.signup")}}" method="POST">
            <label for="username">Enter username: </label>
            <input type="text" id="username" name = "signup_username" required>
            <label for="email">Enter email: </label>
            <input type="text" id="email" name = "signup_email" required>
            <label for="password">Enter password: </label>
            <input type="password" id="password" name = "signup_password" required>
            <input type= "submit" value = "Sign Up">
        </form>
</div><br><br>

<div class="loginForm">
<h3>Login form</h3>
    <form action="{{url_for("auth.login")}}" method="POST">
        <label for="username_email">Enter username or email address: </label>
        <input type="text" id="username_email" name = "username_email" required>
        <label for="password">Enter password: </label>
        <input type="password" id="login_password" name = "login_password" required>
        <input type= "submit" value = "Login">
    </form>
</div>
</div>
{% else %}
<a href={{url_for("auth.logout")}}>Logout</a>
<br>
<div class="container">
<h3>Location Preference:</h3>
<p>{{locationPreference}}</p>
<p>{{locationInfo.locationName}}</p>
<p>{{locationInfo.country}}</p>
</div>
<br>

<div class="container">
<h3>Heat Preference:</h3>
<p>{{heatPreference}}</p>
<a href={{url_for("account.changePreferences")}}>Edit</a>
</div>

{% endif %}

{% endblock %}

app/account/templates/changePreferences.html
{% extends "base.html" %}
{% block body %}
<div class="sleepPreferenceForm">
        <form action="/changePreferences" method="POST">
            <label for="location">Enter location to change to: </label>
            <input type="text" id="newLocation" name = "newLocation"><br>
            <label for="heatPreference">Enter new heatPreference: </label>
            <input type="text" id="heatPreference" name = "heatPreference"><br>
            <input type= "submit" value = "Submit">
        </form>
</div><br><br>
{%endblock body %}

app/account/templates/setPreferences.html
{% extends "base.html" %}

{% block body%}
<h1>Set Your Preferences</h1>
<div class="weatherSubmitDiv">
    <form action="{{url_for('account.submitPreferences')}}" method="POST" class = "weatherPreferenceForm">
            <label for="location">Enter location: </label>
            <input type="text" id="location" name = "location"><br>
            <label for="preference">Select your temperature preferences</label>
        <select name="preference" id="preference">
            <option value="hot">Hot</option>
            <option value="cold">Cold</option>
        </select>
        <input type= "submit" value = "Sign Up">
        </form>
</div>
{% endblock %}